### ISSUE TITLE
setup.py gives TypeError: __init__() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by howff** [PublicaMundi/ckanext-publicamundi#231]
Trying to build the demo-debian branch running through the ansible yml I'm getting
TypeError: __init__() takes exactly 2 arguments (4 given) trying to setup. I can't work out which init is being called and by whom.

$ sudo -u ckaner sh -c '(cd /var/local/ckan/default/pyenv/src/ckan ; ../../bin/python  setup.py develop)'
running develop
running egg_info
writing ckan.egg-info/PKG-INFO
writing namespace_packages to ckan.egg-info/namespace_packages.txt
writing top-level names to ckan.egg-info/top_level.txt
writing dependency_links to ckan.egg-info/dependency_links.txt
writing entry points to ckan.egg-info/entry_points.txt
reading manifest file 'ckan.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'ckanext/*/i18n'
no previously-included directories found matching '.git'
warning: no files found matching 'CHANGELOG.txt'
writing manifest file 'ckan.egg-info/SOURCES.txt'
running build_ext
Creating /var/local/ckan/default/pyenv/lib/python2.7/site-packages/ckan.egg-link (link to .)
ckan 2.2.1 is already the active version in easy-install.pth
Installing ckan-admin script to /var/local/ckan/default/pyenv/bin

Installed /var/local/ckan/default/pyenv/src/ckan
Traceback (most recent call last):
  File "setup.py", line 153, in <module>
    entry_points=entry_points,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/ckan/default/pyenv/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 27, in run
    self.install_for_development()
  File "/var/local/ckan/default/pyenv/local/lib/python2.7/site-packages/setuptools/command/develop.py", line 129, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/var/local/ckan/default/pyenv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by kalxas** [comment]
Our production deployment is based on Debian Wheezy.
Which version of Debian did you try?

**Comment by howff** [comment]
I used Ubuntu 14.04 as that's the closest to Wheezy
$ pip list|grep setupt
setuptools (3.3)
$ dpkg -l |grep setupt
ii  python-setuptools                    3.3-1ubuntu2

**Comment by howff** [comment]
I tried uninstalling setuptools-3.3 (ubuntu) and installing setuptools-0.6.24 (wheezy) but still get the same error.

**Comment by kalxas** [comment]
@drmalex07 have you seen this error before?
I have not seen this on my previous tests.

**Comment by kalxas** [comment]
I actually had success deploying PublicaMundi last year on a Xenial system.

**Comment by drmalex07** [comment]
The error does not remind me of anything.

By the way, our production setup (on debian 7.8 machines) is built on:
Python: 2.7
Pip: 7.0.3
Setuptools: distribute-0.6.24-py2.7
